### PR TITLE
Correcting issue #31 and #33 in combine_supp

### PR DESCRIPTION
**Pull request by statasaurus**
Resolving #31 and #33.

### CODE REVIEW

**Comment by billdenney** [comment]
Thanks for making this.  I understand the rationale for some of the changes, and I have a few questions and thoughts, in addition.

For making an incomplete merge only a warning, I tend to be concerned that most of the time users ignore warnings and only pay attention to errors.  (And, the default R behavior of not showing warnings when there are a lot of warnings encourages this behavior.) If the warning is ignored, then there would be a loss of data. Is there a situation where an incomplete merge would be the desired behavior?

For not always doing that floating point correction, I understand the goal of giving the user control.  My understanding of the package is that it is made to align with the CDISC SDTM standard (or at least this function is).  Is that correct?  If so, I would make the character conversion the default (and no conversion is the optional behavior) because it aligns with the fact that IDVARVAL is defined as character in the standard.

**Comment by statasaurus** [comment]
To your first question, I understand the concern. I know at just our rule is that your code needs to run without errors or warnings. So there isn't much room to just ignore the warning. I made it a warning in part so that people could get the outcome dataset. That way it will potentially be easier to debug. @mstackhouse Do you have a strong feeling on if this should be an error or a warning? 

Yes, this function is meant to align with CDISC, but the primary dataset is what is getting converted to character and CDSIC doesn't require that to be character and in fact the code initially just converted the SUPP IDVARVAL to the type that was present in the primary dataset. So I don't want to force people into this change as the expected functionality is that combine_supp will match the type of the primary dataset for the IDVAR rather than convert the IDVARs to character.

**Review by mstackhouse — CHANGES_REQUESTED** [review]
@statasaurus let me know your thoughts on my comments and if you're good with them, we should update this PR directly.

**Comment by mstackhouse** [comment]
> If supp doesn't have a match in the parent, then the SUPP is non-compliant with CDISC standards. So that's a problem.
> 
> That said, I think that throwing an error and stopping the program makes this hard to debug, so @statasaurus I actually recommend that we:
> 
> * Introduce an option to toggle between error and warning
> * Default to this option throwing an error, and then have the error message state "to debug this issue and identify non-compliant records, set  to "debug"" or something like that.
> 
> I think this satisfies the potential of users ignoring warnings but again I think just throwing an error makes this hard to debug.
> 
> Ok - second issue. Numeric precision. This one is tough... Perhaps we introduce a parameter to combine_supp that offers some precision factor for numeric keys from the primary dataset. It's highly unlikely that a IDVAR in a SUPP would require high numeric precision, because a result variable should never be an identifier key. So rounding shouldn't hurt the dataset. The general logic would have to be something like:
> 
> > If IDVAR is numeric and a precision factor is set, round the IDVAR from the primary dataset prior to merge, and round the IDVARVAL from the SUPP dataset after character to numeric conversion and prior to merge.
> 
> This is unavoidable, because IDVARVAL _has_ to be stored as character, and IDVAR can and should be numeric in some cases. Character to numeric conversions are often the culprit of precision mismatches and it's just part of floating point numbers.
> 
> I've never like SUPP datasets and this conversion issue is a great example of why - but that's not really up for debate here.

@statasaurus instead of an option (because you hate options, I know) we could also make a parameter that bypasses the error. Or open to other thoughts - it just needs to be explicit and somehow feed back information to let a user find out why things aren't merging. Like part of me is thinking like what if it could optionally feed back a list with the anti_join records in one dataset and the merged supp in the second. (This is weird because then this option would feed back a different data type which is not super kosher but meh)

**Comment by billdenney** [comment]
@mstackhouse and @statasaurus Thanks for the feedback here.  As suggested above, my preference is to have an incomplete merge as an error (by default or only an error).

To make the error message clearer to the user, I have some other code that I can adapt to help here if of interest.  Basically, it prints rows that do not merge (up to the first 10 so that the screen isn't scrolling forever) before raising the error.

(And, @mstackhouse , I share your frustration with the SUPP domains design.  I have always wondered why they allowed the SUPP domains rather than just allowing the addition of nonstandard columns where the nonstandard columns names must be called out in some way to ensure that they weren't accidents.  But alas, I wasn't part of the design committee. :) )

**Comment by statasaurus** [comment]
> p doesn't have a match in the parent, then the SUPP is non-compliant with CDISC standards. So that's a problem.
> 
> That said, I think that throwing an error and stopping the program makes this hard to debug, so @statasaurus I actually recommend that we:
> 
> * Introduce an option to toggle between error and warning
> * Default to this option throwing an error, and then have the error message state "to debug this issue and identify non-compliant records, set  to "debug"" or something like that.
> 
> I think this satisfies the potential of users ignoring warnings but again I think just throwing an error makes this hard to debug.
> 
> Ok - second issue. Numeric precision. This one is tough... Perhaps we introduce a parameter to combine_supp that offers some precision factor for numeric keys from the primary dataset. It's highly unlikely that a IDVAR in a SUPP would require high numeric precision, because a result variable should never be an identifier key. So rounding shouldn't hurt the dataset. The general logic would have to be something like:
> 
> > If IDVAR is numeric and a precision factor is set, round the IDVAR from the primary dataset prior to merge, and round the IDVARVAL from the SUPP dataset after character to numeric conversion and prior to merge.
> 
> This is unavoidable, because IDVARVAL _has_ to be stored as character, and IDVAR can and should be numeric in some cases. Character to numeric conversions are often the culprit of precision mismatches and it's just part of floating point numbers.
> 
> I've never like SUPP datasets and this conversion issue is a great example of why - but that's not really

The numeric precision wasn't hard to solve cause we just converted the main data to a character, merge with the supp and then convert back to what type was there before. The question is, should that be on by default or off by default? I have it off by default so there aren't any problems with converting things that shouldn't be converted. 

To the question of warning or error, I didn't realize this was a CDISC requirement. Given that is the case, I am just going to change it to an error. Although it is easier to debug with a warning, I don't think that ease is worth the increased complexity of an additional argument. At the moment it returns a table of with USUBJID's and IDVARS (with the IDVARVAL as the column name) for all rows that didn't merge. I think this will be enough information to allow people to debug

**Comment by billdenney** [comment]
> The numeric precision wasn't hard to solve cause we just converted the main data to a character, merge with the supp and then convert back to what type was there before.

I think it would be preferred not to modify the source data twice to get the desired effect.  The code as written could cause significant downstream issues as the `IDVAR` column will become the mode (instead of the class) of the source data.  As an example, if `IDVAR` is `"LBDTC"` (which I often store as a POSIXct variable), with the current code, the `LBDTC` column will become numeric on output.  I assume that the user would not expect or desire that.

Doing it in a separate column will prevent issues in class/mode detection for columns that are e.g. POSIXt or Date objects (or any others where the mode and the class do not match):

``` r
foo <- Sys.time()
class(foo)
#> [1] "POSIXct" "POSIXt"
mode(foo)
#> [1] "numeric"
as.numeric(foo)
#> [1] 1655728314
as.character(foo)
#> [1] "2022-06-20 08:31:53"
```

<sup>Created on 2022-06-20 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

So, I would suggest not converting the main dataset column to character and to create a new `IDVARVAL` column that is the character representation of the source data within the main dataset.  Then make sure that `supp$IDVARVAL` is also character, merge, and drop the `IDVARVAL` column.  That way, the merge happens as anticipated (without floating point issues) and the source data remains unchanged (without possible issues related to what is, in effect `as.numeric(as.character(main$IDVARVAL))` in some cases.  (https://github.com/billdenney/metatools/blob/637e8ff531bf225616e63971b276aab7090b5c59/R/supp.R#L184-L197 is one way to do that.)

> The question is, should that be on by default or off by default? I have it off by default so there aren't any problems with converting things that shouldn't be converted.

Since `IDVARVAL` being character is required by SDTM, I would suggest that it is on by default.

**Comment by mstackhouse** [comment]
> So, I would suggest not converting the main dataset column to character and to create a new IDVARVAL column that is the character representation of the source data within the main dataset.

@billdenney this is probably the best way to do it - because @statasaurus  converting the data back risks modifying the source data. The numeric precision issues are _coming_ from converting the SUPP.IDVARVAL value to character then back to numeric. So @billdenney's solution is the most robust one. 

I support the error generation - we just have to make sure the error output is presented well enough for debugging. Perhaps we offer a second function that detects the errors (i.e. IDVAR/IDVARVALs not present in parent) and recommend they use that for debugging purposes.

**Comment by billdenney** [comment]
@statasaurus and @mstackhouse , Thanks for the collaboration on this!

**Pull request merged**
